# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

www.tuho.tv	FALSE	/	FALSE	1623283199	__DAYU_PP	ZJfNI2RBmrva2yZzYeYu59f5d865c5a5
